[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/books"
  to = "/api/v1/books.json"
  status = 200

[[redirects]]
  from = "/api/v1/books/"
  to = "/api/v1/books.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
